### ISSUE TITLE
onBlur and onEnter submit error

### ISSUE THREAD

**Issue by rossinspired** [deltablot/malle#11] opened 2024-01-05 22:17 UTC
# Describe the bug

If I have both onBlur and onEnter set to Action.Submit, then I get this error in the Console:
"Uncaught (in promise) DOMException: Failed to execute 'replaceWith' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler? at malle.js:110:23"

onBlur seems to work either way.
But if I change onBlur to Action.Ignore, then onEnter works as expected.

Should it not allow both onBlur and onEnter to use Action.Submit ??

# Information

- malle version: 2.5.2
- Client operating system (e.g: MacOS, Windows, GNU+Linux): macos
- Browser (e.g. firefox, chrome): chrome

**Comment by NicolasCARPi** [comment] 2024-01-05 23:41
Hello, I cannot reproduce this behavior. What is your browser version? Can you reproduce with another browser?

Can you reproduce [on the demo](https://deltablot.github.io/malle/)? I have just added a section "Setting behavior for both Blur action and Enter keypress" with both blur and enter leading to submit. Works fine for me with both Firefox or Chromium.

**Comment by rossinspired** [comment] 2024-01-08 15:48
I'm on an older version of Chrome (Version 120.0.6099.109 (Official Build) (x86_64))
I received the same behavior on safari and firefox.
I downloaded the demo files and received the same behavior.

**Comment by NicolasCARPi** [comment] 2024-01-08 16:27
I'm sorry but without a reproducible bug, it will be hard to fix.

Could you record a video showing the problem? Maybe there is something that we missed in the bug description and that is important. Sometimes I ask for a video and immediatly understand the user problem because they were doing something weird (normal for them, weird for the app).

If it's reproducible with several browsers and also on the demo code, then we can assume the issue is not on your side. But it would still be useful to know:

- what operating system are you using, add complete version number (assuming MacOS)
- what are the versions of firefox and safari?
- can you reproduce on **another computer**? (you can simply browse to the demo website and try it there).
- also you said "I downloaded the demo files", can you try it online on the provided link? (https://deltablot.github.io/malle/ section "Setting behavior for both Blur action and Enter keypress")

I just want to isolate as much as possible the issue.

Also, is it 100% of the time erroring out or sometimes it works?

**Comment by NicolasCARPi** [comment] 2024-11-14 20:03
The bug only appears on Chromium based browsers, not firefox. Version 2.6.2 will contain a fix for this issue!

**Closed** 2024-11-14 20:02 UTC
Labels: not reproducible
